# Generated by Django 4.0.4 on 2022-05-19 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='converter.types')),
            ],
        ),
        migrations.CreateModel(
            name='ConverterLength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_unit', models.FloatField(blank=True, null=True)),
                ('to_unit', models.FloatField(blank=True, null=True)),
                ('types', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='converter.types')),
                ('units', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='converter.units')),
            ],
        ),
    ]
