# Generated by Django 4.0.4 on 2022-04-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Converter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_de', models.CharField(blank=True, max_length=10, unique=True)),
                ('unit_a', models.CharField(blank=True, max_length=10, unique=True)),
            ],
        ),
    ]
