# Generated by Django 4.0.4 on 2022-05-31 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Types',
            new_name='Type',
        ),
        migrations.RenameModel(
            old_name='Units',
            new_name='Unit',
        ),
        migrations.RenameField(
            model_name='converterlength',
            old_name='types',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='converterlength',
            old_name='units',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='types',
            new_name='type',
        ),
    ]
