# Generated by Django 4.0.7 on 2023-05-14 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitto',
            name='type',
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Unit Type', 'verbose_name_plural': 'Unit Types'},
        ),
        migrations.RemoveField(
            model_name='type',
            name='name',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='name',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='type',
        ),
        migrations.AddField(
            model_name='type',
            name='unit_type',
            field=models.SmallIntegerField(choices=[(1, 'Pressure'), (2, 'Length'), (3, 'Volume')], default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='unit',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_exponent',
            field=models.IntegerField(blank=True, null=True, verbose_name='Exponent unit'),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='converter.type', verbose_name='Unit Type'),
        ),
        migrations.DeleteModel(
            name='ConverterLength',
        ),
        migrations.DeleteModel(
            name='UnitTo',
        ),
    ]
