# Generated by Django 4.0.4 on 2022-06-02 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_rename_types_type_rename_units_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='converterlength',
            name='unit',
        ),
        migrations.AddField(
            model_name='converterlength',
            name='unit_length',
            field=models.ForeignKey(blank=True, choices=[('millimeter', 'millimeter'), ('centimeter', 'centimeter'), ('meter', 'meter'), ('kilometer', 'kilometer')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='converter.unit'),
        ),
        migrations.AlterField(
            model_name='converterlength',
            name='type',
            field=models.ForeignKey(blank=True, choices=[('Length', 'Length'), ('Pressure', 'Pressure')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='converter.type'),
        ),
    ]
