# Generated by Django 4.0.7 on 2023-05-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_remove_unitto_type_alter_type_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='description',
            field=models.CharField(max_length=30, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='type',
            name='unit_type',
            field=models.SmallIntegerField(choices=[(1, 'Pressure'), (2, 'Length'), (3, 'Volume')], default=1),
        ),
    ]
