# Generated by Django 4.0.4 on 2022-04-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_rename_unit_a_converter_a_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Converter_length',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_unit', models.FloatField(unique=True)),
                ('a_unit', models.FloatField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Converter',
        ),
    ]
