# Generated by Django 4.0.4 on 2022-04-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_converter_length_delete_converter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConverterLength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_unit', models.FloatField(blank=True, unique=True)),
                ('a_unit', models.FloatField(blank=True)),
                ('types', models.CharField(blank=True, choices=[('Length', 'Length'), ('Pressure', 'Pressure')], default='Length', max_length=100)),
                ('unit_types_length', models.CharField(blank=True, choices=[('millimeter', 'millimeter'), ('centimeter', 'centimeter'), ('meter', 'meter'), ('kilometer', 'kilometer')], default='millimeter', max_length=100)),
                ('unit_types_pressure', models.CharField(blank=True, choices=[('psi', 'psi'), ('pascal', 'pascal'), ('atm', 'atmosphere')], default='psi', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Converter_length',
        ),
    ]
