# Generated by Django 4.0.4 on 2022-06-02 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_remove_converterlength_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='converterlength',
            old_name='unit_length',
            new_name='unit',
        ),
    ]
