# Generated by Django 4.0.7 on 2023-05-15 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_type_description_alter_type_unit_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='unit_type',
        ),
        migrations.AddField(
            model_name='type',
            name='code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='type',
            name='description',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='converter.type', verbose_name='Unit Type'),
        ),
    ]
