# Generated by Django 4.0.7 on 2023-05-19 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0004_remove_type_unit_type_type_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Type', 'verbose_name_plural': 'Types'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
        migrations.AlterField(
            model_name='unit',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_exponent',
            field=models.FloatField(blank=True, null=True, verbose_name='Exponent unit'),
        ),
    ]
