# Generated by Django 4.0.4 on 2022-04-19 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0004_converterlength_delete_converter_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='converterlength',
            old_name='de_unit',
            new_name='from_unit',
        ),
        migrations.RenameField(
            model_name='converterlength',
            old_name='a_unit',
            new_name='to_unit',
        ),
    ]
