# Generated by Django 4.0.4 on 2022-06-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0004_rename_unit_length_converterlength_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='type',
        ),
        migrations.RemoveField(
            model_name='converterlength',
            name='type',
        ),
        migrations.RemoveField(
            model_name='converterlength',
            name='unit',
        ),
        migrations.AddField(
            model_name='converterlength',
            name='types',
            field=models.CharField(blank=True, choices=[('Length', 'Length'), ('Pressure', 'Pressure')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='converterlength',
            name='unit_types_from',
            field=models.CharField(blank=True, choices=[('millimeter', 'millimeter'), ('centimeter', 'centimeter'), ('meter', 'meter'), ('kilometer', 'kilometer'), ('psi', 'psi'), ('pascal', 'pascal'), ('atm', 'atmosphere')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='converterlength',
            name='unit_types_to',
            field=models.CharField(blank=True, choices=[('millimeter', 'millimeter'), ('centimeter', 'centimeter'), ('meter', 'meter'), ('kilometer', 'kilometer'), ('psi', 'psi'), ('pascal', 'pascal'), ('atm', 'atmosphere')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
