# Generated by Django 4.0.4 on 2022-06-02 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0005_remove_unit_type_remove_converterlength_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='converterlength',
            old_name='types',
            new_name='type',
        ),
    ]
