# Generated by Django 4.0.4 on 2022-04-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0005_rename_de_unit_converterlength_from_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converterlength',
            name='to_unit',
            field=models.FloatField(),
        ),
    ]
