# Generated by Django 4.0.4 on 2022-04-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0006_alter_converterlength_to_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converterlength',
            name='to_unit',
            field=models.FloatField(blank=True, null=True, unique=True),
        ),
    ]
