# Generated by Django 4.0.4 on 2022-06-03 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0007_type_remove_converterlength_unit_types_to_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='converterlength',
            old_name='unit_types_from',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='types',
            new_name='type',
        ),
    ]
