# Generated by Django 4.0.4 on 2022-06-03 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0008_rename_unit_types_from_converterlength_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='converter.type')),
            ],
        ),
        migrations.AddField(
            model_name='converterlength',
            name='unit_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='converter.unitto'),
        ),
    ]
