# Generated by Django 4.0.4 on 2022-06-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0009_unitto_converterlength_unit_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converterlength',
            name='to_unit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
