# Generated by Django 4.0.4 on 2022-04-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0009_alter_converterlength_from_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converterlength',
            name='types',
            field=models.CharField(blank=True, default='Length', max_length=100),
        ),
        migrations.AlterField(
            model_name='converterlength',
            name='unit_types_from',
            field=models.CharField(blank=True, default='millimeter', max_length=100),
        ),
        migrations.AlterField(
            model_name='converterlength',
            name='unit_types_to',
            field=models.CharField(blank=True, default='millimeter', max_length=100),
        ),
    ]
