# Generated by Django 4.0.4 on 2022-06-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0010_alter_converterlength_to_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
