# Generated by Django 4.0.4 on 2022-04-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0010_alter_converterlength_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converterlength',
            name='from_unit',
            field=models.FloatField(),
        ),
    ]
