# Generated by Django 4.0.4 on 2022-04-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0012_remove_converterlength_unit_types_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converterlength',
            name='unit_types_from',
            field=models.CharField(blank=True, choices=[('millimeter', 'millimeter'), ('centimeter', 'centimeter'), ('meter', 'meter'), ('kilometer', 'kilometer')], default='millimeter', max_length=100),
        ),
        migrations.AlterField(
            model_name='converterlength',
            name='unit_types_to',
            field=models.CharField(blank=True, choices=[('millimeter', 'millimeter'), ('centimeter', 'centimeter'), ('meter', 'meter'), ('kilometer', 'kilometer')], default='millimeter', max_length=100),
        ),
    ]
