# Generated by Django 4.0.4 on 2022-04-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0013_alter_converterlength_unit_types_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converterlength',
            name='to_unit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='converterlength',
            name='unit_types_from',
            field=models.CharField(blank=True, default='millimeter', max_length=100),
        ),
        migrations.AlterField(
            model_name='converterlength',
            name='unit_types_to',
            field=models.CharField(blank=True, default='millimeter', max_length=100),
        ),
    ]
